### ISSUE TITLE
Add edit views for Tour and PointOfInterest

### ISSUE THREAD

**Issue by donni106** [ikuseiGmbH/smart-village-app-cms#16]
In an upcoming update, categories will be added to the CMS and every resource. To edit categories for existing entries, edit views are necessary for all resources.
As user of the CMS it is currently not possible to show or edit entries of tours and points of interest.
This can be implemented like existing views for news items and events.

**Comment by donni106** [comment]
implemented for `PointOfInterest` with #35.
also needed to do a lot of side stuff.
for `Tour` it should be "just" copy & paste adjustments based on `PointOfInterest` i think @theresasteinmetz. but we should still talk about the sense of you doing it.

**Comment by theresasteinmetz** [comment]
Verweis auf https://github.com/ikuseiGmbH/smart-village-app-cms/pull/49
