### ISSUE TITLE
Saving of a POI creates a price field

### ISSUE THREAD

**Issue by pwilimzig** [ikuseiGmbH/smart-village-app-cms#43]
Bei der Eingabe eines Ortes über das CMS wird scheinbar automatisch eine (leere) Preiskategorie erstellt. Jedenfalls erscheint ein entsprechender Block in der App, obwohl keine Preise hinterlegt sind. Bei importierten Orten tritt dieser Fehler nicht auf.

**Comment by pwilimzig** [comment]
Siehe 'Integrative Kindertagesstätte „Märchenland“' (https://cms.herzberg-elster.smart-village.app/point_of_interests/564/edit)

**Comment by donni106** [comment]
Wie #44, bereits bekannt, ebenso bei Adresse.
